[package]
name = "DN2D"
edition = "2021"
version = "0.1.0"

[dependencies]
notify = "5.0.0"
timely = "0.25.0"
petgraph = "0.8.3"
serde_json = "1.0"
differential-dataflow = "0.18.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }